// File zum Testen der erstellten Routen

POST http://localhost:3001/setup/plz
Content-Type: application/json

{
  "plz": "22880"
}

//Trennzeichen zwischen verschiedenen Request-Tests:
###

GET http://localhost:3001/call/nina

###

POST http://localhost:3001/setup/regionalKey
Content-Type: application/json

{
  "regionalKey": "010560050050"
}