// File zum Testen der erstellten Routen

POST http://localhost:3001/setup/plz
Content-Type: application/json

{
  "plz": "22880"
}

//Trennzeichen zwischen verschiedenen Request-Tests:
###

//GET http://localhost:3001/call/nina
GET http://localhost:3001/nina/call

###

GET http://localhost:3001/nina/test

###

POST http://localhost:3001/setup/regionalKey
Content-Type: application/json

{
  "regionalKey": "010560050050"
}

###

POST http://localhost:3001/setup/geo-coords
Content-Type: application/json

{
  "lat": 53.58,
  "lon": 9.70
}

###

GET http://localhost:3001/weather/call